### ISSUE TITLE
Update the "discuss" page to reflect the correct locations for discussion

### ISSUE THREAD

**Issue by proffalken** [r9y-dev/site#15]
#11 reformatted the `/discuss` page and it [now looks great!](https://r9y.dev/discuss/), however it does not appear to link to the Discord server.

We need to update the page and ensure that the various contact/discussion links are pointing to the correct locations or are added/removed as appropriate.

**Comment by stevemcghee** [comment]
how about amending the top header for:  map, discord/chat, monthly-discuss

then we'd add a small page about the discord, allowing it to grow etc.
might have to disambiguate the term "discuss" along the way (one is realtime chat, one is monthly videoconf)

**Comment by stevemcghee** [comment]
adding /chat and /video in #17
